# Generated by Django 6.0.5 on 2026-05-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('event_type', models.CharField(choices=[('WEDDING', 'Weddings'), ('BIRTHDAY', 'Birthdays'), ('CORPORATE', 'Corporate Events'), ('MEETING', 'Meetings'), ('BURIAL', 'Burial Ceremony'), ('GENERAL', 'General Events')], max_length=50)),
                ('primary_color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('venue_name', models.CharField(max_length=255)),
                ('guest_count', models.IntegerField()),
                ('budget_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_palette', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('BOOKED', 'Booked')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
