# Generated by Django 6.0.5 on 2026-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='town',
            field=models.CharField(default='Yaoundé', max_length=100),
        ),
    ]
